from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


COMMENT_MARKER = "<!-- monthly-ai-review -->"
DEFAULT_API_URL = "https://api.github.com"


def extract_latest_assistant_text(execution_log: list[dict[str, Any]]) -> str:
    for turn in reversed(execution_log):
        if turn.get("type") != "assistant":
            continue

        content_items = turn.get("message", {}).get("content", [])
        text_parts = [
            item.get("text", "").strip()
            for item in content_items
            if item.get("type") == "text" and item.get("text", "").strip()
        ]
        if text_parts:
            return "\n\n".join(text_parts).strip()

    raise ValueError("No assistant review text found in Claude execution log")


def build_comment_body(review_text: str, run_url: str | None = None) -> str:
    body = f"{COMMENT_MARKER}\n## Claude Monthly Strategy Review\n\n{review_text.strip()}"
    if run_url:
        body += f"\n\n---\n_Generated by AI Monthly Review workflow: {run_url}_"
    return body


def github_request(
    method: str,
    url: str,
    token: str,
    payload: dict[str, Any] | None = None,
) -> Any:
    data = None
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "crypto-leader-rotation-monthly-ai-review",
    }
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"

    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    with urllib.request.urlopen(request) as response:
        charset = response.headers.get_content_charset("utf-8")
        raw = response.read().decode(charset)
        return json.loads(raw) if raw else None


def upsert_issue_comment(
    *,
    api_url: str,
    repo: str,
    issue_number: int,
    token: str,
    body: str,
) -> None:
    comments_url = f"{api_url}/repos/{repo}/issues/{issue_number}/comments"
    comments = github_request("GET", comments_url, token)
    existing = next(
        (
            comment
            for comment in comments
            if COMMENT_MARKER in comment.get("body", "")
        ),
        None,
    )

    if existing:
        github_request(
            "PATCH",
            f"{api_url}/repos/{repo}/issues/comments/{existing['id']}",
            token,
            {"body": body},
        )
        print(f"Updated issue comment {existing['id']}")
        return

    github_request("POST", comments_url, token, {"body": body})
    print(f"Created issue comment for issue #{issue_number}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract Claude review text from execution output and upsert an issue comment.",
    )
    parser.add_argument("--repo", required=True, help="owner/repo")
    parser.add_argument("--issue-number", required=True, type=int)
    parser.add_argument("--execution-file", required=True, type=Path)
    parser.add_argument("--api-url", default=DEFAULT_API_URL)
    parser.add_argument("--run-url", default="")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("GITHUB_TOKEN is required", file=sys.stderr)
        return 1

    execution_log = json.loads(args.execution_file.read_text(encoding="utf-8"))
    review_text = extract_latest_assistant_text(execution_log)
    body = build_comment_body(review_text, args.run_url or None)

    try:
        upsert_issue_comment(
            api_url=args.api_url.rstrip("/"),
            repo=args.repo,
            issue_number=args.issue_number,
            token=token,
            body=body,
        )
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        print(f"GitHub API request failed: {exc.code} {detail}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
